### ISSUE TITLE
No oodle.dll in most recent version of D2?

### ISSUE THREAD

**Issue by wkearney99** [MontagueM/DestinyUnpackerCPP#5]
Is there a way to get this working with the most recent version of D2?  As of 2/2023?

There's no oodle.dll in there presently.

**Comment by MontagueM** [comment]
still there, bin/x64/oo2core_9_win64.dll

**Comment by wkearney99** [comment]
the code expects it to be named for an older version.

296: hOodleDll = LoadLibrary(L"oo2core_8_win64.dll");

With that edited (along with the source and output paths)and the dll copied with it, the console outputs:

>DestinyUnpackerCPP.exe 
c:/Program Files (x86)/Steam/steamapps/common/Destiny 2/packages///w64_sr_open_world_011f_0.pkg
c:/Program Files (x86)/Steam/steamapps/common/Destiny 2/packages///w64_sr_open_world_011f_1.pkg
c:/Program Files (x86)/Steam/steamapps/common/Destiny 2/packages///w64_sr_open_world_011f_2.pkg
c:/Program Files (x86)/Steam/steamapps/common/Destiny 2/packages///w64_sr_open_world_011f_3.pkg
c:/Program Files (x86)/Steam/steamapps/common/Destiny 2/packages///w64_sr_open_world_011f_4.pkg
c:/Program Files (x86)/Steam/steamapps/common/Destiny 2/packages///w64_sr_open_world_011f_5.pkg
c:/Program Files (x86)/Steam/steamapps/common/Destiny 2/packages///w64_sr_open_world_011f_6.pkg

And the output directory contains a sole directory named 011f which has 2,921 files with a ".bin" extension.

Is there something more expected?
